/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package directorioescuelas;

import java.awt.Color;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Administrador
 */
public class CampañasAsignadas extends javax.swing.JFrame {

    /**
     * Creates new form CampañasAsignadas
     */
    public CampañasAsignadas() {
        initComponents();
        getContentPane().setBackground(Color.LIGHT_GRAY);
        cargarTabla();
    }

     private void cargarTabla(){
    
        IntercampañasDAO dao = new
        IntercampañasDAO();
        
        tablacampana_asignadas.setModel(dao.mostrarAsignaciones());
        
        //ocultar columnas de los id
        
        tablacampana_asignadas.getColumnModel().getColumn(0).setMinWidth(0);
        tablacampana_asignadas.getColumnModel().getColumn(0).setMaxWidth(0);
        tablacampana_asignadas.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        tablacampana_asignadas.getColumnModel().getColumn(1).setMinWidth(0);
        tablacampana_asignadas.getColumnModel().getColumn(1).setMaxWidth(0);
        tablacampana_asignadas.getColumnModel().getColumn(1).setPreferredWidth(0);
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Imagen_intercamp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacampana_asignadas = new javax.swing.JTable();
        btneliminar_asig = new javax.swing.JButton();
        btnactualizar_asig = new javax.swing.JButton();
        btnregresar_asig = new javax.swing.JButton();
        btnasigcam_imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DIRECTORIO ESCOLAR TEXCOCO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("\"VER CAMPAÑAS ASIGNADAS A ESCUELAS\"");

        Imagen_intercamp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpeg"))); // NOI18N

        tablacampana_asignadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablacampana_asignadas);

        btneliminar_asig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btneliminar_asig.setText("ELIMINAR ASIGNACIÓN");
        btneliminar_asig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar_asigActionPerformed(evt);
            }
        });

        btnactualizar_asig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnactualizar_asig.setText("ACTUALIZAR");
        btnactualizar_asig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizar_asigActionPerformed(evt);
            }
        });

        btnregresar_asig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnregresar_asig.setText("REGRESAR");
        btnregresar_asig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar_asigActionPerformed(evt);
            }
        });

        btnasigcam_imprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnasigcam_imprimir.setText("IMPRIMIR");
        btnasigcam_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasigcam_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Imagen_intercamp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnregresar_asig)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btneliminar_asig)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnactualizar_asig)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnasigcam_imprimir))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(Imagen_intercamp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregresar_asig)
                    .addComponent(btnactualizar_asig)
                    .addComponent(btneliminar_asig)
                    .addComponent(btnasigcam_imprimir))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminar_asigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar_asigActionPerformed
        int fila =
        tablacampana_asignadas.getSelectedRow();

        if (fila >= 0) {
            int idCampaña =
            Integer.parseInt(tablacampana_asignadas.getValueAt(fila,0).toString());
            int idEscuela =
            Integer.parseInt(tablacampana_asignadas.getValueAt(fila,1).toString());

            int confirmacion =
            JOptionPane.showConfirmDialog(null, "¿Deseas eliminar esta Asignación", "Confirmar", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION){
                IntercampañasDAO dao = new
                IntercampañasDAO();

                dao.eliminarAsignacion(idCampaña, idEscuela);

                JOptionPane.showMessageDialog(null,"Asignación eliminada");
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null,"Selecciona una fila");
            }
        }
    }//GEN-LAST:event_btneliminar_asigActionPerformed

    private void btnactualizar_asigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizar_asigActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnactualizar_asigActionPerformed

    private void btnregresar_asigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar_asigActionPerformed
        inter_campana inter = new
        inter_campana();
        inter.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnregresar_asigActionPerformed

    private void btnasigcam_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasigcam_imprimirActionPerformed
        
      try {
        
         boolean completo =
         tablacampana_asignadas.print(
         JTable.PrintMode.FIT_WIDTH,
         new MessageFormat("Reporte de Campañas Asignadas"),
         new MessageFormat("Página {0}")
                 
         );
         
         if (completo){
         JOptionPane.showMessageDialog(null, "Impresión Completada");
         } else {
         JOptionPane.showMessageDialog(null, "Impresión Cancelada");
         }
        
        } catch (PrinterException e){
         JOptionPane.showMessageDialog(null, "Error al Imprimir" + e.getMessage());
        }  
    }//GEN-LAST:event_btnasigcam_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampañasAsignadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampañasAsignadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampañasAsignadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampañasAsignadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampañasAsignadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen_intercamp;
    private javax.swing.JButton btnactualizar_asig;
    private javax.swing.JButton btnasigcam_imprimir;
    private javax.swing.JButton btneliminar_asig;
    private javax.swing.JButton btnregresar_asig;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablacampana_asignadas;
    // End of variables declaration//GEN-END:variables
}
