/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package directorioescuelas;

import java.awt.Color;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrador
 */
public class Escuelas_Registro extends javax.swing.JFrame {

    /**
     * Creates new form Escuelas_Registro
     */
    public Escuelas_Registro() {
        initComponents();
        getContentPane().setBackground(Color.LIGHT_GRAY);
        
         CEscuelas objetoEscuela = new CEscuelas ();
         objetoEscuela.MostrarEscuelas(tbescuelas);
         
         jtext_id.setEditable(false);
         configurarTabla();
    }
    
    private void configurarTabla(){
    
    tbescuelas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    
    tbescuelas.getColumnModel().getColumn(0).setPreferredWidth(50); // id
    tbescuelas.getColumnModel().getColumn(1).setPreferredWidth(220); // nombre
    tbescuelas.getColumnModel().getColumn(2).setPreferredWidth(300); // direccion
    tbescuelas.getColumnModel().getColumn(3).setPreferredWidth(90); // telefono
    tbescuelas.getColumnModel().getColumn(4).setPreferredWidth(80);  // matricula
    tbescuelas.getColumnModel().getColumn(5).setPreferredWidth(90);  // nivel
    tbescuelas.getColumnModel().getColumn(6).setPreferredWidth(180);  //zona
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtext_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtextnombre_escuelas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtextdireccion_escuelas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtexttelefono_escuelas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtextmatricula = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbescuelas = new javax.swing.JTable();
        btnguardar_escuelas = new javax.swing.JButton();
        jtextzona_escuelas = new javax.swing.JTextField();
        jtextnivel_escuelas = new javax.swing.JTextField();
        btneditar_escuelas = new javax.swing.JButton();
        btneliminar_escuelas = new javax.swing.JButton();
        btnimprimir_escuelas = new javax.swing.JButton();
        btnregresar_escuelas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpeg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DIRECTORIO ESCOLAR TEXCOCO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("\"REGISTRO-ESCUELAS\"");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NOMBRE:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DIRECCIÓN:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("TELÉFONO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("MATRÍCULA:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("NIVEL:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("ZONA:");

        tbescuelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbescuelas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbescuelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbescuelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbescuelas);

        btnguardar_escuelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguardar_escuelas.setText("GUARDAR");
        btnguardar_escuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar_escuelasActionPerformed(evt);
            }
        });

        btneditar_escuelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btneditar_escuelas.setText("EDITAR");
        btneditar_escuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditar_escuelasActionPerformed(evt);
            }
        });

        btneliminar_escuelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btneliminar_escuelas.setText("ELIMINAR");
        btneliminar_escuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar_escuelasActionPerformed(evt);
            }
        });

        btnimprimir_escuelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnimprimir_escuelas.setText("IMPRIMIR");
        btnimprimir_escuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimir_escuelasActionPerformed(evt);
            }
        });

        btnregresar_escuelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnregresar_escuelas.setText("REGRESAR");
        btnregresar_escuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar_escuelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtextnivel_escuelas))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtexttelefono_escuelas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtextmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(118, 118, 118)
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtextzona_escuelas, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 55, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(61, 61, 61)
                                                    .addComponent(jLabel3))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtextdireccion_escuelas))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jtext_id))
                                                .addComponent(jLabel5))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtextnombre_escuelas)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnguardar_escuelas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btneditar_escuelas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btneliminar_escuelas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnimprimir_escuelas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnregresar_escuelas)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtext_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtextnombre_escuelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtextdireccion_escuelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtexttelefono_escuelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtextmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jtextzona_escuelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextnivel_escuelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar_escuelas)
                    .addComponent(btneditar_escuelas)
                    .addComponent(btneliminar_escuelas)
                    .addComponent(btnimprimir_escuelas)
                    .addComponent(btnregresar_escuelas))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardar_escuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar_escuelasActionPerformed
        CEscuelas objetoEscuela = new CEscuelas();
        objetoEscuela.InsertarEscuela(jtextnombre_escuelas, jtextdireccion_escuelas, jtexttelefono_escuelas, jtextmatricula, jtextnivel_escuelas, jtextzona_escuelas);
        objetoEscuela.MostrarEscuelas(tbescuelas);
        configurarTabla();
        objetoEscuela.LimpiarCampos(jtext_id,jtextnombre_escuelas, jtextdireccion_escuelas, jtexttelefono_escuelas, jtextmatricula, jtextnivel_escuelas, jtextzona_escuelas);
    }//GEN-LAST:event_btnguardar_escuelasActionPerformed

    private void btnregresar_escuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar_escuelasActionPerformed
        Menu_principal menu = new
        Menu_principal();
        menu.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnregresar_escuelasActionPerformed

    private void tbescuelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbescuelasMouseClicked
       CEscuelas objetoEscuela = new CEscuelas();
       objetoEscuela.SeleccionarEscuela(tbescuelas, jtext_id, jtextnombre_escuelas, jtextdireccion_escuelas, jtexttelefono_escuelas, jtextmatricula, jtextnivel_escuelas, jtextzona_escuelas);
    }//GEN-LAST:event_tbescuelasMouseClicked

    private void btneditar_escuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditar_escuelasActionPerformed
       CEscuelas objetoEscuela = new CEscuelas();
       objetoEscuela.EditarEscuela(jtext_id,jtextnombre_escuelas, jtextdireccion_escuelas, jtexttelefono_escuelas, jtextmatricula, jtextnivel_escuelas, jtextzona_escuelas);
       objetoEscuela.MostrarEscuelas(tbescuelas);
       configurarTabla();
       objetoEscuela.LimpiarCampos(jtext_id,jtextnombre_escuelas, jtextdireccion_escuelas, jtexttelefono_escuelas, jtextmatricula, jtextnivel_escuelas, jtextzona_escuelas);
    }//GEN-LAST:event_btneditar_escuelasActionPerformed

    private void btneliminar_escuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar_escuelasActionPerformed
      CEscuelas objetoEscuela = new CEscuelas();
      objetoEscuela.EliminarEscuela(jtext_id);
      objetoEscuela.MostrarEscuelas(tbescuelas);
      configurarTabla();
      objetoEscuela.LimpiarCampos(jtext_id,jtextnombre_escuelas, jtextdireccion_escuelas, jtexttelefono_escuelas, jtextmatricula, jtextnivel_escuelas, jtextzona_escuelas);
    }//GEN-LAST:event_btneliminar_escuelasActionPerformed

    private void btnimprimir_escuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimir_escuelasActionPerformed
        new Thread(() -> {
            try {
                tbescuelas.print (
            JTable.PrintMode.FIT_WIDTH,
                        new
                    MessageFormat("Reporte de escuelas"),
                    new MessageFormat("Página {0}")
                        );
            }
            catch (PrinterException e){
              SwingUtilities.invokeLater(()
                      ->
            JOptionPane.showMessageDialog(this, "Error al imprimir")
                      
              );
            
           }
        }).start();
    }//GEN-LAST:event_btnimprimir_escuelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Escuelas_Registro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar_escuelas;
    private javax.swing.JButton btneliminar_escuelas;
    private javax.swing.JButton btnguardar_escuelas;
    private javax.swing.JButton btnimprimir_escuelas;
    private javax.swing.JButton btnregresar_escuelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtext_id;
    private javax.swing.JTextField jtextdireccion_escuelas;
    private javax.swing.JTextField jtextmatricula;
    private javax.swing.JTextField jtextnivel_escuelas;
    private javax.swing.JTextField jtextnombre_escuelas;
    private javax.swing.JTextField jtexttelefono_escuelas;
    private javax.swing.JTextField jtextzona_escuelas;
    private javax.swing.JTable tbescuelas;
    // End of variables declaration//GEN-END:variables
}
