/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package directorioescuelas;

import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Escuelas_Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Escuelas_Reportes
     */
    public Escuelas_Reportes() {
        initComponents();
        getContentPane().setBackground(Color.LIGHT_GRAY);
        cargarNiveles();
    
    }
    
    public void cargarNiveles(){
    
    cmbNivel.removeAllItems();
    cmbNivel.addItem("Todos");
    cmbNivel.addItem("Preescolar");
    cmbNivel.addItem("Primaria");
    cmbNivel.addItem("Secundaria");
    cmbNivel.addItem("Bachillerato");
    cmbNivel.addItem("Universidad");
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbreportes = new javax.swing.JTable();
        jbtnbuscar_reportes = new javax.swing.JButton();
        btngenerar_reportes = new javax.swing.JButton();
        btnexportar_reportes = new javax.swing.JButton();
        jbtnregresar_reportes = new javax.swing.JButton();
        cmbNivel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpeg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DIRECTORIO ESCOLAR TEXCOCO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("\"REPORTES SISTEMA\"");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("NIVEL EDUCATIVO:");

        tbreportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbreportes);

        jbtnbuscar_reportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnbuscar_reportes.setText("BUSCAR");
        jbtnbuscar_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbuscar_reportesActionPerformed(evt);
            }
        });

        btngenerar_reportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btngenerar_reportes.setText("GENERAR REPORTE EN PDF");
        btngenerar_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerar_reportesActionPerformed(evt);
            }
        });

        btnexportar_reportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexportar_reportes.setText("EXPORTAR DOCUMENTO A EXCEL");
        btnexportar_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportar_reportesActionPerformed(evt);
            }
        });

        jbtnregresar_reportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnregresar_reportes.setText("Regresar");
        jbtnregresar_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnregresar_reportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btngenerar_reportes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnexportar_reportes)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnregresar_reportes)))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(jLabel3))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnbuscar_reportes)
                                .addGap(68, 68, 68))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnbuscar_reportes))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngenerar_reportes)
                    .addComponent(btnexportar_reportes)
                    .addComponent(jbtnregresar_reportes))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnregresar_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnregresar_reportesActionPerformed
        Menu_principal menu = new
        Menu_principal();
        menu.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jbtnregresar_reportesActionPerformed

    private void btnexportar_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportar_reportesActionPerformed
        
        JFileChooser chooser = new
        JFileChooser();
        chooser.setDialogTitle("Guardar reporte en Excel");
        
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int seleccion =
        chooser.showSaveDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo =
            chooser.getSelectedFile();
            
            try (FileWriter fw = new FileWriter(archivo + ".xls")){
                DefaultTableModel modelo = (DefaultTableModel)
                tbreportes.getModel();
                
                //Encabezados
                for (int i = 0; i <
                modelo.getColumnCount(); i++) {
               fw.write(modelo.getColumnName(i) + "\t");
                }
                fw.write("\n");
                // Filas
                for (int i = 0; i<
                modelo.getRowCount(); i++) {
                for (int j = 0; j < modelo.getColumnCount(); j++){
                
                fw.write(modelo.getValueAt(i,j).toString() + "\t");
                }
                fw.write("\n");
                }
                
            JOptionPane.showMessageDialog(this, "Archivo Excel exportado correctamente");
                } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al exportar: " + e.getMessage());        
            }
        }
        
    }//GEN-LAST:event_btnexportar_reportesActionPerformed

    private void jbtnbuscar_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbuscar_reportesActionPerformed
        String nivel =
        cmbNivel.getSelectedItem().toString();
        buscarEscuelasPorNivelCombo com = new  buscarEscuelasPorNivelCombo();
        DefaultTableModel modelo =
        com.buscarPorNivel(nivel);
        tbreportes.setModel(modelo);
    }//GEN-LAST:event_jbtnbuscar_reportesActionPerformed

    private void btngenerar_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerar_reportesActionPerformed

ExportarPDF.exportarJTable(tbreportes);
    }//GEN-LAST:event_btngenerar_reportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escuelas_Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexportar_reportes;
    private javax.swing.JButton btngenerar_reportes;
    private javax.swing.JComboBox<String> cmbNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnbuscar_reportes;
    private javax.swing.JButton jbtnregresar_reportes;
    private javax.swing.JTable tbreportes;
    // End of variables declaration//GEN-END:variables
}
