/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package directorioescuelas;

import java.awt.Color;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Administrador
 */
public class Escuelas_Eventos extends javax.swing.JFrame {

    /**
     * Creates new form Escuelas_Eventos
     */
    public Escuelas_Eventos() {
        initComponents();
        getContentPane().setBackground(Color.LIGHT_GRAY);
        
        CEventos objetoEvento = new CEventos ();
        objetoEvento.MostrarEventos(tbeventos);
        
        jtextid_eventos.setEditable(false);
        configurarTabla();
    }
    
    private void configurarTabla(){
    
    tbeventos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    
    tbeventos.getColumnModel().getColumn(0).setPreferredWidth(80); // id
    tbeventos.getColumnModel().getColumn(1).setPreferredWidth(200); // nombre
    tbeventos.getColumnModel().getColumn(2).setPreferredWidth(400); // direccion
    tbeventos.getColumnModel().getColumn(3).setPreferredWidth(110); // telefono
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtextid_eventos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtextnombre_eventos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtextdescripcion_eventos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtextfecha_eventos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbeventos = new javax.swing.JTable();
        btnguardar_eventos = new javax.swing.JButton();
        btneditar_eventos = new javax.swing.JButton();
        btneliminar_eventos = new javax.swing.JButton();
        btnimprimir_eventos = new javax.swing.JButton();
        btnregresar_eventos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpeg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DIRECTORIO ESCOLAR TEXCOCO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("\"REGISTRO-EVENTOS CÍVICOS\"");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ID EVENTO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NOMBRE:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DESCRIPCIÓN:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("FECHA:");

        tbeventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbeventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbeventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbeventos);

        btnguardar_eventos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguardar_eventos.setText("GUARDAR");
        btnguardar_eventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar_eventosActionPerformed(evt);
            }
        });

        btneditar_eventos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btneditar_eventos.setText("EDITAR");
        btneditar_eventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditar_eventosActionPerformed(evt);
            }
        });

        btneliminar_eventos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btneliminar_eventos.setText("ELIMINAR");
        btneliminar_eventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar_eventosActionPerformed(evt);
            }
        });

        btnimprimir_eventos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnimprimir_eventos.setText("IMPRIMIR");
        btnimprimir_eventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimir_eventosActionPerformed(evt);
            }
        });

        btnregresar_eventos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnregresar_eventos.setText("REGRESAR");
        btnregresar_eventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar_eventosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtextid_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtextnombre_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(63, 63, 63))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(91, 91, 91))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnguardar_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btneditar_eventos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btneliminar_eventos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnimprimir_eventos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnregresar_eventos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtextdescripcion_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtextfecha_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtextid_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtextnombre_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtextdescripcion_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextfecha_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar_eventos)
                    .addComponent(btneditar_eventos)
                    .addComponent(btneliminar_eventos)
                    .addComponent(btnimprimir_eventos)
                    .addComponent(btnregresar_eventos))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardar_eventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar_eventosActionPerformed
        CEventos objetoEvento = new CEventos();
        objetoEvento.InsertarEvento(jtextnombre_eventos, jtextdescripcion_eventos, jtextfecha_eventos);
        objetoEvento.MostrarEventos(tbeventos);
        configurarTabla();
        objetoEvento.LimpiarCampos(jtextid_eventos,jtextnombre_eventos, jtextdescripcion_eventos, jtextfecha_eventos);
    }//GEN-LAST:event_btnguardar_eventosActionPerformed

    private void btnregresar_eventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar_eventosActionPerformed
        Menu_principal menu = new
        Menu_principal();
        menu.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnregresar_eventosActionPerformed

    private void btneditar_eventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditar_eventosActionPerformed
       CEventos objetoEvento = new CEventos();
       objetoEvento.EditarEvento(jtextid_eventos,jtextnombre_eventos, jtextdescripcion_eventos, jtextfecha_eventos);
       objetoEvento.MostrarEventos(tbeventos); 
       configurarTabla();
       objetoEvento.LimpiarCampos(jtextid_eventos,jtextnombre_eventos, jtextdescripcion_eventos, jtextfecha_eventos);
    }//GEN-LAST:event_btneditar_eventosActionPerformed

    private void tbeventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbeventosMouseClicked
     CEventos objetoEvento = new CEventos();
     objetoEvento.SeleccionarEvento(tbeventos, jtextid_eventos, jtextnombre_eventos, jtextdescripcion_eventos,jtextfecha_eventos );
    }//GEN-LAST:event_tbeventosMouseClicked

    private void btneliminar_eventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar_eventosActionPerformed
      CEventos objetoEvento = new CEventos();
      objetoEvento.EliminarEvento(jtextid_eventos);
      objetoEvento.MostrarEventos(tbeventos);
      configurarTabla();
      objetoEvento.LimpiarCampos(jtextid_eventos,jtextnombre_eventos, jtextdescripcion_eventos, jtextfecha_eventos);
    }//GEN-LAST:event_btneliminar_eventosActionPerformed

    private void btnimprimir_eventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimir_eventosActionPerformed
     
        try {
        
         boolean completo =
         tbeventos.print(
         JTable.PrintMode.FIT_WIDTH,
         new MessageFormat("Reporte de Eventos Registrados"),
         new MessageFormat("Página {0}")
                 
         );
         
         if (completo){
         JOptionPane.showMessageDialog(null, "Impresión Completada");
         } else {
         JOptionPane.showMessageDialog(null, "Impresión Cancelada");
         }
        
        } catch (PrinterException e){
         JOptionPane.showMessageDialog(null, "Error al Imprimir" + e.getMessage());
        }
    }//GEN-LAST:event_btnimprimir_eventosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escuelas_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escuelas_Eventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar_eventos;
    private javax.swing.JButton btneliminar_eventos;
    private javax.swing.JButton btnguardar_eventos;
    private javax.swing.JButton btnimprimir_eventos;
    private javax.swing.JButton btnregresar_eventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtextdescripcion_eventos;
    private javax.swing.JTextField jtextfecha_eventos;
    private javax.swing.JTextField jtextid_eventos;
    private javax.swing.JTextField jtextnombre_eventos;
    private javax.swing.JTable tbeventos;
    // End of variables declaration//GEN-END:variables
}
