/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package directorioescuelas;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author Administrador
 */
public class Escuelas_campanas extends javax.swing.JFrame {

    /**
     * Creates new form Escuelas_campanas
     */
    public Escuelas_campanas() {
        initComponents();
        getContentPane().setBackground(Color.LIGHT_GRAY);
        
        CCampañas objetoCampaña = new CCampañas ();
        objetoCampaña.MostrarCampañas(tbcampanas);
        
        jtextid_campana.setEditable(false);
        configurarTabla();
    }
    
    private void configurarTabla(){
    
    tbcampanas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    
    tbcampanas.getColumnModel().getColumn(0).setPreferredWidth(50); // id
    tbcampanas.getColumnModel().getColumn(1).setPreferredWidth(220); // nombre
    tbcampanas.getColumnModel().getColumn(2).setPreferredWidth(350); // direccion
    tbcampanas.getColumnModel().getColumn(3).setPreferredWidth(90); // telefono
    tbcampanas.getColumnModel().getColumn(4).setPreferredWidth(80);  // matricula
    tbcampanas.getColumnModel().getColumn(5).setPreferredWidth(100);  // nivel
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtextid_campana = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtextnombre_campana = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtextdescripcion_campanas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtextinicio_campanas = new javax.swing.JTextField();
        jtextfin_campanas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtextnivel_campanas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcampanas = new javax.swing.JTable();
        btnguardar_campanas = new javax.swing.JButton();
        btneditar_campanas = new javax.swing.JButton();
        btneliminar_campanas = new javax.swing.JButton();
        btnimprimir_campanas = new javax.swing.JButton();
        btnregresar_campanas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpeg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DIRECTORIO ESCOLAR TEXCOCO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("\"REGISTRO-CAMPAÑAS\"");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NOMBRE:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DESCRIPCIÓN:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("FECHA INICIO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FECHA FIN:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("NIVEL:");

        tbcampanas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbcampanas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcampanasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcampanas);

        btnguardar_campanas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguardar_campanas.setText("GUARDAR");
        btnguardar_campanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar_campanasActionPerformed(evt);
            }
        });

        btneditar_campanas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btneditar_campanas.setText("EDITAR");
        btneditar_campanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditar_campanasActionPerformed(evt);
            }
        });

        btneliminar_campanas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btneliminar_campanas.setText("ELIMINAR");
        btneliminar_campanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar_campanasActionPerformed(evt);
            }
        });

        btnimprimir_campanas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnimprimir_campanas.setText("IMPRIMIR");
        btnimprimir_campanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimir_campanasActionPerformed(evt);
            }
        });

        btnregresar_campanas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnregresar_campanas.setText("REGRESAR");
        btnregresar_campanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar_campanasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtextfin_campanas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtextinicio_campanas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtextnombre_campana, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtextid_campana, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtextdescripcion_campanas, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtextnivel_campanas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnguardar_campanas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btneditar_campanas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btneliminar_campanas)
                            .addGap(18, 18, 18)
                            .addComponent(btnimprimir_campanas)
                            .addGap(107, 107, 107)
                            .addComponent(btnregresar_campanas))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtextinicio_campanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtextfin_campanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtextid_campana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtextnombre_campana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtextdescripcion_campanas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtextnivel_campanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar_campanas)
                    .addComponent(btneditar_campanas)
                    .addComponent(btneliminar_campanas)
                    .addComponent(btnimprimir_campanas)
                    .addComponent(btnregresar_campanas))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardar_campanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar_campanasActionPerformed
       CCampañas objetoCampaña = new CCampañas();
       objetoCampaña.InsertarCampaña(jtextnombre_campana, jtextdescripcion_campanas, jtextinicio_campanas,jtextfin_campanas,jtextnivel_campanas);
       objetoCampaña.MostrarCampañas(tbcampanas);
       configurarTabla();
       objetoCampaña.LimpiarCampos(jtextid_campana,jtextnombre_campana, jtextdescripcion_campanas, jtextinicio_campanas, jtextfin_campanas, jtextnivel_campanas);
    }//GEN-LAST:event_btnguardar_campanasActionPerformed

    private void btnregresar_campanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar_campanasActionPerformed
        Menu_principal menu = new
        Menu_principal();
        menu.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnregresar_campanasActionPerformed

    private void tbcampanasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcampanasMouseClicked
        CCampañas objetoCampaña = new CCampañas();
        objetoCampaña.SeleccionarCampaña(tbcampanas, jtextid_campana,jtextnombre_campana, jtextdescripcion_campanas, jtextinicio_campanas,jtextfin_campanas,jtextnivel_campanas);
    }//GEN-LAST:event_tbcampanasMouseClicked

    private void btneditar_campanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditar_campanasActionPerformed
       CCampañas objetoCampaña = new CCampañas();
       objetoCampaña.EditarCampaña(jtextid_campana,jtextnombre_campana, jtextdescripcion_campanas, jtextinicio_campanas, jtextfin_campanas, jtextnivel_campanas);
       objetoCampaña.MostrarCampañas(tbcampanas);
       configurarTabla();
       objetoCampaña.LimpiarCampos(jtextid_campana,jtextnombre_campana, jtextdescripcion_campanas, jtextinicio_campanas, jtextfin_campanas, jtextnivel_campanas);
    }//GEN-LAST:event_btneditar_campanasActionPerformed

    private void btneliminar_campanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar_campanasActionPerformed
      CCampañas objetoCampaña = new CCampañas();
      objetoCampaña.EliminarCampaña(jtextid_campana);
      objetoCampaña.MostrarCampañas(tbcampanas);
      configurarTabla();
      objetoCampaña.LimpiarCampos(jtextid_campana,jtextnombre_campana, jtextdescripcion_campanas, jtextinicio_campanas, jtextfin_campanas, jtextnivel_campanas);
    }//GEN-LAST:event_btneliminar_campanasActionPerformed

    private void btnimprimir_campanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimir_campanasActionPerformed
try {

    boolean full =
    tbcampanas.print(
    JTable.PrintMode.FIT_WIDTH,
    new MessageFormat("Reporte de Campañas"),
    new MessageFormat("Página {0}")
            
    );
    
    if (full){
    JOptionPane.showMessageDialog(null, "Impresión Completada");
    } else {
    JOptionPane.showMessageDialog(null, "Impresión Cancelada");
    }

}   catch (PrinterException e){
    JOptionPane.showMessageDialog(null, "Error al Imprimir" + e.getMessage());
}     
        
    }//GEN-LAST:event_btnimprimir_campanasActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escuelas_campanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escuelas_campanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escuelas_campanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escuelas_campanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escuelas_campanas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar_campanas;
    private javax.swing.JButton btneliminar_campanas;
    private javax.swing.JButton btnguardar_campanas;
    private javax.swing.JButton btnimprimir_campanas;
    private javax.swing.JButton btnregresar_campanas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtextdescripcion_campanas;
    private javax.swing.JTextField jtextfin_campanas;
    private javax.swing.JTextField jtextid_campana;
    private javax.swing.JTextField jtextinicio_campanas;
    private javax.swing.JTextField jtextnivel_campanas;
    private javax.swing.JTextField jtextnombre_campana;
    private javax.swing.JTable tbcampanas;
    // End of variables declaration//GEN-END:variables
}
