/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package directorioescuelas;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class inter_eventos extends javax.swing.JFrame {

    /**
     * Creates new form inter_eventos
     */
    public inter_eventos() {
        initComponents();
        getContentPane().setBackground(Color.LIGHT_GRAY);
        EventoDAO dao = new EventoDAO();
        jcom_sel_evento.setModel(dao.cargarEventos());
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Imagen_inter = new javax.swing.JLabel();
        btnregresar_inter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcom_sel_evento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtextasignar_escuelaevento = new javax.swing.JTextField();
        btnbuscar_escuela_evento = new javax.swing.JButton();
        btnasignar_evento = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbesceventos_interm = new javax.swing.JTable();
        btnasignacion_evento = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Imagen_inter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpeg"))); // NOI18N

        btnregresar_inter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnregresar_inter.setText("Regresar");
        btnregresar_inter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar_interActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DIRECTORIO ESCOLAR TEXCOCO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("\"ASIGNACIÓN EVENTOS A ESCUELAS\"");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Selecciona el Evento:");

        jcom_sel_evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcom_sel_eventoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Escribe la Escuela a Asignar a Evento:");

        jtextasignar_escuelaevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextasignar_escuelaeventoActionPerformed(evt);
            }
        });

        btnbuscar_escuela_evento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbuscar_escuela_evento.setText("Buscar");
        btnbuscar_escuela_evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar_escuela_eventoActionPerformed(evt);
            }
        });

        btnasignar_evento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnasignar_evento.setText("Asignar");
        btnasignar_evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasignar_eventoActionPerformed(evt);
            }
        });

        tbesceventos_interm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbesceventos_interm);

        btnasignacion_evento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnasignacion_evento.setText("Ver escuelas asignadas");
        btnasignacion_evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasignacion_eventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbuscar_escuela_evento)
                .addGap(191, 191, 191))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Imagen_inter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jcom_sel_evento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(166, 166, 166))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(btnasignar_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56)
                                    .addComponent(btnasignacion_evento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnregresar_inter))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtextasignar_escuelaevento, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Imagen_inter, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcom_sel_evento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtextasignar_escuelaevento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscar_escuela_evento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnasignar_evento)
                    .addComponent(btnregresar_inter)
                    .addComponent(btnasignacion_evento))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresar_interActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar_interActionPerformed
        Menu_principal menu = new
        Menu_principal();
        menu.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnregresar_interActionPerformed

    private void jcom_sel_eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcom_sel_eventoActionPerformed
        
    }//GEN-LAST:event_jcom_sel_eventoActionPerformed

    private void btnbuscar_escuela_eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar_escuela_eventoActionPerformed
        
        String texto = jtextasignar_escuelaevento.getText();
        
        EscuelaDAO dao = new EscuelaDAO();
        tbesceventos_interm.setModel(dao.buscarEscuelas(texto));
    }//GEN-LAST:event_btnbuscar_escuela_eventoActionPerformed

    private void btnasignar_eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasignar_eventoActionPerformed
        try {
            
        Evento eventoSeleccionado = (Evento) jcom_sel_evento.getSelectedItem();
        int idEvento =
        eventoSeleccionado.getIdEvento();
        
        int fila =
        tbesceventos_interm.getSelectedRow();
        
        if (fila == -1){
        JOptionPane.showMessageDialog(null, "Seleccione una escuela");
        return;
        }
        
        int idEscuela =
        Integer.parseInt(tbesceventos_interm.getValueAt(fila, 0).toString());
        
        CConexion cc = new CConexion();
        Connection con =
        cc.establecerConexion();
        
        String sql = " INSERT INTO Escuela_eventos (id_evento, id_escuela) VALUES (?,?)";
        
        PreparedStatement ps =
        con.prepareStatement(sql);
        ps.setInt(1, idEvento);
        ps.setInt(2, idEscuela);
        
        ps.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "Evento asignado correctamente");
        
        
        } catch (Exception e){
        JOptionPane.showMessageDialog(null, "No se pudo asignar el evento a escuela: " + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnasignar_eventoActionPerformed

    private void btnasignacion_eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasignacion_eventoActionPerformed
        EventosAsignados p = new EventosAsignados();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnasignacion_eventoActionPerformed

    private void jtextasignar_escuelaeventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextasignar_escuelaeventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextasignar_escuelaeventoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inter_eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inter_eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inter_eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inter_eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inter_eventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen_inter;
    private javax.swing.JButton btnasignacion_evento;
    private javax.swing.JButton btnasignar_evento;
    private javax.swing.JButton btnbuscar_escuela_evento;
    private javax.swing.JButton btnregresar_inter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<Evento> jcom_sel_evento;
    private javax.swing.JTextField jtextasignar_escuelaevento;
    private javax.swing.JTable tbesceventos_interm;
    // End of variables declaration//GEN-END:variables
}
