/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package directorioescuelas;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class inter_campana extends javax.swing.JFrame {

    /**
     * Creates new form inter_campana
     */
    public inter_campana() {
        initComponents();
        getContentPane().setBackground(Color.LIGHT_GRAY);
        CampañaDAO dao = new CampañaDAO();
        jcombo_sel_campana.setModel(dao.cargarCampañas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen_campana = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcombo_sel_campana = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtextasignar_campana = new javax.swing.JTextField();
        btnbuscar_escuela_campana = new javax.swing.JButton();
        btnasignar_campana = new javax.swing.JButton();
        btnregresar_asignarcam = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbesccamp_interm = new javax.swing.JTable();
        btnasignacion_campana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagen_campana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpeg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DIRECTORIO ESCOLAR TEXCOCO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("\"ASIGNACIÓN CAMPAÑAS A ESCUELAS\"");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Selecciona la Campaña:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Escribe la Escuela a Asignar a Campaña:");

        btnbuscar_escuela_campana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbuscar_escuela_campana.setText("Buscar");
        btnbuscar_escuela_campana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar_escuela_campanaActionPerformed(evt);
            }
        });

        btnasignar_campana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnasignar_campana.setText("Asignar");
        btnasignar_campana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasignar_campanaActionPerformed(evt);
            }
        });

        btnregresar_asignarcam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnregresar_asignarcam.setText("Regresar");
        btnregresar_asignarcam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar_asignarcamActionPerformed(evt);
            }
        });

        tbesccamp_interm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbesccamp_interm);

        btnasignacion_campana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnasignacion_campana.setText("Ver escuelas asignadas");
        btnasignacion_campana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasignacion_campanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagen_campana, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4)
                                            .addComponent(jcombo_sel_campana, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel3))
                                            .addComponent(jtextasignar_campana))
                                        .addGap(32, 32, 32))
                                    .addComponent(jLabel2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(btnbuscar_escuela_campana)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnasignar_campana)
                        .addGap(110, 110, 110)
                        .addComponent(btnasignacion_campana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnregresar_asignarcam))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcombo_sel_campana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagen_campana, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtextasignar_campana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscar_escuela_campana)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnasignacion_campana)
                    .addComponent(btnasignar_campana)
                    .addComponent(btnregresar_asignarcam))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresar_asignarcamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar_asignarcamActionPerformed
        Menu_principal menu = new
        Menu_principal();
        menu.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnregresar_asignarcamActionPerformed

    private void btnbuscar_escuela_campanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar_escuela_campanaActionPerformed
         
        String texto = jtextasignar_campana.getText();
        
        EscuelacampDAO dao = new EscuelacampDAO();
        tbesccamp_interm.setModel(dao.buscarEscuelas(texto));
    }//GEN-LAST:event_btnbuscar_escuela_campanaActionPerformed

    private void btnasignar_campanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasignar_campanaActionPerformed
       
        try {
            
        Campaña campañaSeleccionada = (Campaña) jcombo_sel_campana.getSelectedItem();
        int idCampaña =
        campañaSeleccionada.getIdCampaña();
        
        int fila =
        tbesccamp_interm.getSelectedRow();
        
        if (fila == -1){
        JOptionPane.showMessageDialog(null, "Seleccione una escuela");
        return;
        }
        
        int idEscuela =
        Integer.parseInt(tbesccamp_interm.getValueAt(fila, 0).toString());
        
        CConexion cc = new CConexion();
        Connection con =
        cc.establecerConexion();
        
        String sql = " INSERT INTO Escuela_campañas (id_campaña, id_escuela) VALUES (?,?)";
        
        PreparedStatement ps =
        con.prepareStatement(sql);
        ps.setInt(1, idCampaña);
        ps.setInt(2, idEscuela);
        
        ps.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "Campaña asignada correctamente");
        
        
        } catch (Exception e){
        JOptionPane.showMessageDialog(null, "No se pudo asignar la campaña a la escuela: " + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnasignar_campanaActionPerformed

    private void btnasignacion_campanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasignacion_campanaActionPerformed
        CampañasAsignadas p = new CampañasAsignadas();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnasignacion_campanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inter_campana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inter_campana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inter_campana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inter_campana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inter_campana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnasignacion_campana;
    private javax.swing.JButton btnasignar_campana;
    private javax.swing.JButton btnbuscar_escuela_campana;
    private javax.swing.JButton btnregresar_asignarcam;
    private javax.swing.JLabel imagen_campana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Campaña> jcombo_sel_campana;
    private javax.swing.JTextField jtextasignar_campana;
    private javax.swing.JTable tbesccamp_interm;
    // End of variables declaration//GEN-END:variables
}
